# Generated by Django 6.1 on 2026-09-10 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0013_constituency_ward_constituency_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICTOfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ict_officers', to='home.constituency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ict_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ICT Officer Profile',
            },
        ),
    ]
