# Generated by Django 6.1 on 2026-08-21 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('upload', 'Upload'), ('sync', 'Sync'), ('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('model_type', models.CharField(choices=[('clerk', 'Clerk'), ('kit', 'KIEMS Kit'), ('ward', 'Ward'), ('entry', 'Daily Entry'), ('phase', 'Phase')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(max_length=200)),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('import', 'Import'), ('export', 'Export')], max_length=20)),
                ('model_type', models.CharField(choices=[('clerk', 'Clerk'), ('kit', 'KIEMS Kit'), ('ward', 'Ward'), ('entry', 'Daily Entry')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_success', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_export_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import/Export Log',
                'verbose_name_plural': 'Import/Export Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
