# Generated by Django 6.1 on 2026-08-20 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ward__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KIEMSKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_name', models.CharField(max_length=50)),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_clerks', models.ManyToManyField(blank=True, related_name='kits', to='home.clerk')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kits', to='home.ward')),
            ],
            options={
                'ordering': ['ward__name', 'kit_name'],
            },
        ),
        migrations.CreateModel(
            name='VRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('device_token', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vras', to='home.ward')),
            ],
            options={
                'verbose_name': 'VRA',
                'verbose_name_plural': 'VRAs',
                'ordering': ['ward__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyKIEMSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('venue', models.CharField(max_length=150)),
                ('total_registered', models.PositiveIntegerField(default=0)),
                ('total_transferred', models.PositiveIntegerField(default=0)),
                ('total_deleted', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('uploaded', models.BooleanField(default=False)),
                ('office_updated_by', models.CharField(blank=True, max_length=150)),
                ('office_updated_at', models.DateTimeField(blank=True, null=True)),
                ('kiems_kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_entries', to='home.kiemskit')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_entries', to='home.phase')),
                ('vra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_entries', to='home.vra')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_entries', to='home.ward')),
            ],
            options={
                'ordering': ['-entry_date', 'ward__name'],
            },
        ),
        migrations.AddField(
            model_name='clerk',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clerks', to='home.ward'),
        ),
        migrations.AddIndex(
            model_name='kiemskit',
            index=models.Index(fields=['ward', 'status'], name='home_kiemsk_ward_id_d98e96_idx'),
        ),
        migrations.AddIndex(
            model_name='dailykiemsentry',
            index=models.Index(fields=['ward', 'entry_date'], name='home_dailyk_ward_id_0d1ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='dailykiemsentry',
            index=models.Index(fields=['phase', 'entry_date'], name='home_dailyk_phase_i_2a80d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailykiemsentry',
            constraint=models.UniqueConstraint(fields=('kiems_kit', 'phase', 'entry_date', 'vra'), name='unique_kit_phase_day_vra'),
        ),
    ]
