# Generated by Django 6.1 on 2026-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailykiemsentry',
            name='registered_female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailykiemsentry',
            name='registered_male',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailykiemsentry',
            name='registered_other',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailykiemsentry',
            name='total_updated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
