# Generated by Django 6.1 on 2026-08-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dailykiemsentry_registered_female_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailykiemsentry',
            name='total_updated',
        ),
    ]
