# Generated by Django 6.1 on 2026-08-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_dailykiemsentry_total_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailykiemsentry',
            name='registered_other',
        ),
    ]
