# Generated by Django 6.1 on 2026-08-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_dailykiemsentry_registered_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailykiemsentry',
            name='total_deleted',
        ),
    ]
