# Generated by Django 6.1 on 2026-08-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_dailykiemsentry_total_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailykiemsentry',
            name='total_updated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
