# Generated by Django 6.1 on 2026-08-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_whatsappgroup_whatsappsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='whatsappsetting',
            options={'ordering': ['user__username']},
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='whatsappsetting',
            name='notify_grand_total',
            field=models.BooleanField(default=True, help_text='Send grand total when all wards submit'),
        ),
        migrations.AlterField(
            model_name='whatsappsetting',
            name='notify_daily',
            field=models.BooleanField(default=True, help_text='Send daily report'),
        ),
        migrations.AlterField(
            model_name='whatsappsetting',
            name='notify_edit',
            field=models.BooleanField(default=True, help_text='Send notification when VRA edits'),
        ),
        migrations.AlterField(
            model_name='whatsappsetting',
            name='notify_vra',
            field=models.BooleanField(default=True, help_text='Send notification when VRA submits'),
        ),
    ]
