# Generated by Django 6.1 on 2026-08-29 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_device_deviceburnlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerk',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clerk',
            name='device_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dailykiemsentry',
            name='clerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_entries', to='home.clerk'),
        ),
        migrations.AddField(
            model_name='device',
            name='clerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='home.clerk'),
        ),
    ]
