# Generated by Django 6.1 on 2026-09-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_clerk_device_fingerprint_clerk_device_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailykiemsentry',
            name='entry_type',
            field=models.CharField(choices=[('VENUE', 'Venue Mapping Only'), ('REGISTRATION', 'Registration Entry')], default='REGISTRATION', max_length=20),
        ),
    ]
