# Generated by Django 6.1 on 2026-09-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_dailykiemsentry_entry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('total_wards', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
