# Generated by Django 6.1 on 2026-09-11 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_constituency_ward_constituency_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappgroup',
            name='constituency',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global/superadmin-only groups.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_groups', to='home.constituency'),
        ),
    ]
