# Generated by Django 6.1 on 2026-09-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_whatsappgroup_constituency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='burn_date',
            field=models.DateTimeField(blank=True, help_text='When the device was authorized (burned-in).', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='burn_notes',
            field=models.TextField(blank=True, help_text='Notes recorded at authorization time.'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_burned',
            field=models.BooleanField(default=False, help_text='True = authorized (burned-in). False = not authorized.'),
        ),
        migrations.AlterField(
            model_name='deviceburnlog',
            name='action',
            field=models.CharField(choices=[('AUTHORIZE', 'Authorized'), ('REVOKE', 'Authorization Revoked'), ('BURN', 'Burned (legacy)'), ('UNBURN', 'Unburned (legacy)'), ('REVOKE_ACCESS', 'Access Revoked (legacy)'), ('RESTORE', 'Access Restored (legacy)')], max_length=20),
        ),
    ]
