# Generated by Django 6.1 on 2026-09-11 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_device_burn_date_alter_device_burn_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending — wards still submitting'), ('READY', 'Ready — all wards in, waiting to send'), ('SENDING', 'Sending — locked by a worker'), ('SENT', 'Sent — done'), ('FAILED', 'Failed — will be retried')], default='PENDING', max_length=12)),
                ('total_wards', models.PositiveIntegerField(default=0)),
                ('submitted_wards', models.PositiveIntegerField(default=0)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('message_hash', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_states', to='home.constituency')),
            ],
            options={
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['status', 'report_date'], name='home_dailyr_status_bde26e_idx'), models.Index(fields=['constituency', '-report_date'], name='home_dailyr_constit_9bc861_idx')],
                'constraints': [models.UniqueConstraint(fields=('constituency', 'report_date'), name='unique_daily_report_per_constituency_day')],
            },
        ),
    ]
