# Generated by Django 6.1 on 2026-09-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_dailyreportstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
