# Generated by Django 6.1 on 2026-09-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_ward_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_run_at', models.DateTimeField(auto_now=True)),
                ('last_summary', models.JSONField(blank=True, default=dict)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
