# Generated by Django 6.1 on 2026-09-11 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_cronheartbeat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappgroup',
            options={'ordering': ['constituency__name', 'name']},
        ),
        migrations.AlterField(
            model_name='whatsappgroup',
            name='constituency',
            field=models.ForeignKey(blank=True, help_text='Constituency this group belongs to. Leave blank ONLY for genuinely global groups (national ops, superadmin broadcasts).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_groups', to='home.constituency'),
        ),
        migrations.AddConstraint(
            model_name='whatsappgroup',
            constraint=models.UniqueConstraint(fields=('constituency', 'name'), name='unique_group_name_per_constituency'),
        ),
    ]
