# Generated by Django 6.1 on 2026-09-24 06:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_whatsappgroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_date', models.DateField(db_index=True)),
                ('venue', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_schedules', to='home.clerk')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_schedules', to='home.constituency')),
                ('kiems_kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_schedules', to='home.kiemskit')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_schedules', to='home.phase')),
                ('vra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_schedules', to='home.vra')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_schedules', to='home.ward')),
            ],
            options={
                'ordering': ['-schedule_date', 'ward__name', 'kiems_kit__kit_name'],
                'indexes': [models.Index(fields=['constituency', 'schedule_date'], name='home_moveme_constit_6789f3_idx'), models.Index(fields=['ward', 'schedule_date'], name='home_moveme_ward_id_bfd4d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('kiems_kit', 'schedule_date'), name='unique_kit_movement_per_day')],
            },
        ),
        migrations.CreateModel(
            name='MovementScheduleState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending — wards still submitting'), ('READY', 'Ready — all wards in'), ('SENDING', 'Sending — locked by a worker'), ('SENT', 'Sent'), ('FAILED', 'Failed — will retry')], default='PENDING', max_length=12)),
                ('total_wards', models.PositiveIntegerField(default=0)),
                ('submitted_wards', models.PositiveIntegerField(default=0)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('message_hash', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_schedule_states', to='home.constituency')),
            ],
            options={
                'ordering': ['-schedule_date'],
                'indexes': [models.Index(fields=['status', 'schedule_date'], name='home_moveme_status_e3cceb_idx')],
                'constraints': [models.UniqueConstraint(fields=('constituency', 'schedule_date'), name='unique_movement_schedule_per_constituency_day')],
            },
        ),
    ]
