# Generated by Django 6.1 on 2026-09-24 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_movementschedule_movementschedulestate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementScheduleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('PER_KIT', 'Per-kit submission'), ('GRAND', 'Grand report (all wards)'), ('MANUAL', 'Manual send by ICT officer')], max_length=10)),
                ('group_id', models.CharField(blank=True, max_length=100)),
                ('group_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('sent_ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_schedule_logs', to='home.constituency')),
                ('kiems_kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_schedule_logs', to='home.kiemskit')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_schedule_logs', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_schedule_logs', to='home.ward')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['constituency', '-created_at'], name='home_moveme_constit_f468ee_idx'), models.Index(fields=['schedule_date', 'kind'], name='home_moveme_schedul_16a654_idx')],
            },
        ),
    ]
