# Generated by Django 6.1 on 2026-09-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_county_constituency_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailykiemsentry',
            name='total_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
